### ISSUE TITLE
[BUG]search_web页面出现贴吧信息时parse_web错误

### ISSUE THREAD

**Issue by wuhuanyan** [BaiduSpider/BaiduSpider#10]
**描述该问题**

搜索『石家庄』、『中海油』等关键字时，如果有贴吧信息则无法解析页面内容。

**复现该问题**

```python
from baiduspider import BaiduSpider
from pprint import pprint

results = self.search_web('石家庄', 1)['results']
```

**预期结果**

1、增加对贴吧信息的支持
2、在baiduspider/parser.py 约第200行位置，增加对『result』变量是否存在『tpl』属性的先决判断。

**实际结果**

```python
ERROR log 228 Internal Server Error: /crawling/
Traceback (most recent call last):
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/admin/Downloads/python_projects/work_project/rosefinch/rosefinch/utils/jwt_auth.py", line 234, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/admin/Downloads/python_projects/work_project/rosefinch/rosefinch/apps/crawling/views.py", line 26, in post
    res = Baidu().my_search_web(request.data['keyword'], request.data['page'])
  File "/Users/admin/Downloads/python_projects/work_project/rosefinch/rosefinch/apps/crawling/web_sites/baidu/baidu.py", line 7, in my_search_web
    results = self.search_web(query, pn)['results']
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/baiduspider/__init__.py", line 182, in search_web
    self._handle_error(error)
  File "/anaconda3/envs/rosefinch/lib/python3.6/site-packages/baiduspider/_spider.py", line 71, in _handle_error
    raise error
baiduspider.errors.UnknownError: 'tpl'
```

**系统**

- 操作系统: MacOS 10.13.3
- Python版本: Python 3.6.8 :: Anaconda, Inc.
- BaiduSpider： 0.0.3

**其他描述**

无。

**Comment by samzhangjy** [comment]
该issue已经在最新的commit中修复。请重新安装BaiduSpider（最新版0.0.5）以获得修复后的BaiduSpider。如果还有问题，请重新开启issue。
