### ISSUE TITLE
[BUG] 频繁报错…… in parse_baike_block……AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by photkey** [BaiduSpider/BaiduSpider#107]
```
Traceback (most recent call last):
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\parser\subparser.py", line 120, in parse_baike_block
    b_cover = baike.find("div", class_="c-span3").find("img")["src"]
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevScript\SEO\check_word.py", line 65, in <module>
    check_flow()
  File "D:\DevScript\SEO\check_word.py", line 54, in check_flow
    word_total,checkList = baduSearch(wid,word)
  File "D:\DevScript\SEO\check_word.py", line 7, in baduSearch
    spider = BaiduSpider(cookie=get_cookie()).search_web(query=word)
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\__init__.py", line 452, in search_web
    self._handle_error(error, "BaiduSpider", "parse-web")
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\_spider.py", line 90, in _handle_error
    raise err
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\__init__.py", line 448, in search_web
    results = self.parser.parse_web(content, exclude=exclude)
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\parser\__init__.py", line 79, in parse_web
    baike = self.webSubParser.parse_baike_block(baike)
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\util.py", line 18, in wrapper
    raise err
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\util.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "D:\Develop\Anaconda\lib\site-packages\baiduspider\parser\subparser.py", line 125, in parse_baike_block
    baike.find("div", class_="op-bk-polysemy-imgWrap")
AttributeError: 'NoneType' object has no attribute 'find'
```
python 刚入门的小白，看不太懂报错信息，感觉大概是解析百科的结果时出错，但不知道该怎么解决？
创建BaiduSpider实例的语句：`spider = BaiduSpider(cookie=get_cookie()).search_web(query=word)`

**Comment by samzhangjy** [comment]
duplicate of #106 .

**Comment by samzhangjy** [comment]
issue已在最新版本（v1.0.2.2）中修复。
