### ISSUE TITLE
[BUG] BaiduSpider.search_news() 函数报错

### ISSUE THREAD

**Issue by HarderThenHarder** [BaiduSpider/BaiduSpider#139]
**描述该问题**

调用spider.search_news(query='python')时，代码报错：
```python
from baiduspider import BaiduSpider
from pprint import pprint

spider = BaiduSpider()

res = spider.search_news(query='python')
res = res.plain
```

错误信息：

```shell
Traceback (most recent call last):
  File "/home/map/users/xxxx/queryBaiduSearch/main.py", line 6, in <module>
    res = spider.search_news(query='python')
  File "/home/xxx/users/xxx/anaconda3/envs/scrapy/lib/python3.9/site-packages/baiduspider/__init__.py", line 770, in search_news
    pages = self._calc_pages(result["total"], self.RESULTS_PER_PAGE["news"])
KeyError: 'total'
```

**问题追查**

问题出在baiduSpider/__init__.py文件：770行，尝试调用 result["total"]，但 result 并未正常返回。
进一步追查，发现是[这个函数](https://github.com/BaiduSpider/BaiduSpider/blob/ef10da78497f6438deed3f119ecc0cd0a0cc91ad/baiduspider/__init__.py#L763)内部发生错误，百度新闻页面代码已经修改，[这一行](https://github.com/BaiduSpider/BaiduSpider/blob/ef10da78497f6438deed3f119ecc0cd0a0cc91ad/baiduspider/parser/__init__.py#L556)和[这一行](https://github.com/BaiduSpider/BaiduSpider/blob/ef10da78497f6438deed3f119ecc0cd0a0cc91ad/baiduspider/parser/__init__.py#L564)需要对应的修改：
```python
...
# total = int(
#     bs.find("div", id="wrapper_wrapper")
#     .find("span", class_="nums")
#     .text.split("资讯", 1)[-1]
 #     .split("篇", 1)[0]
#     .replace(",", "")
# )

# 修改为 ->

 total = int(
            bs.find("div", id="wrapper_wrapper")
            .find("span", class_="nums")
            .text.split("资讯", 1)[-1]
            .split("篇", 1)[0]
            .replace(",", "")
            .replace("个", "")
        )


# data = (
#            bs.find("div", id="content_left")
#            .findAll("div")[1]
#            .findAll("div", class_="result-op")
#        )

# 修改为 ->
data = (
            bs.find("div", id="content_left")
            .findAll("div", class_="result-op c-container xpath-log new-pmd")
        )
```

最后，为了增强鲁棒性，我在[这里](https://github.com/BaiduSpider/BaiduSpider/blob/ef10da78497f6438deed3f119ecc0cd0a0cc91ad/baiduspider/parser/__init__.py#L583)对每个参数都做了try-except，以保证程序不会报错。

**实际结果**

代码修改完成后，成功获取返回数据：

```shell
[{'author': None,
  'cover': 'https://t8.baidu.com/it/u=32967610,4123884830&fm=217&app=125&size=f242,162&n=0&g=0n&f=JPEG?s=A14AB35746A34F0D7CB5E8640300E031&sec=1651236167&t=33e712348feb5dcb0b8c925f6e9e0037',
  'date': '2小时前',
  'des': '为切实加强“五一”假期道路交通安全管理工作,进一步消除道路交通安全隐患,预防和减少道路交通事故,推动事故多发路段及安全隐患点段整治取得实效,改善辖区道路交通安全通行条件。4月27...',
  'title': '泾州高速公路大队联合路政部门开展道路隐患排查治理工作',
  'url': 'https://new.qq.com/omn/20220428/20220428A0A4OU00.html'},
 {'author': None,
  'cover': 'https://t11.baidu.com/it/u=3075863716,172019023&fm=30&app=106&size=f242,162&n=0&g=0n&f=JPEG?s=4FDA678040805AED422C1572030080B0&sec=1651236167&t=511e1c693996ba76959a2b15ede3cf5a',
  'date': '2小时前',
  'des': '我觉得在城市道路开车最怕的不是大货车,而是电瓶车,  '
         '大货车看着虽然有点可怕,但大货车基本都比较守规矩,遵守交通规则,而很多电瓶车转弯变道都很随意,没有什么观察,也基本不打转向灯,感...',
  'title': '路上开车一定要远离它!比大货车还危险,提高意识,注意避开',
  'url': 'https://baijiahao.baidu.com/s?id=1729270385036210724&wfr=spider&for=pc'},
 {'author': None,
  'cover': None,
  'date': '3小时前',
  'des': '目前瀍涧大道(丝路大道至衡山路)段道路已施工完毕,为方便此路段居民出行,公交集团将于5月2日起恢复45路在此路段的通行,回程增设杨冢站、瀍涧大道党湾立交桥东站、瀍涧大道秦岭路口东站、瀍涧大道衡山路口东站;取消衡山路立交桥北站、衡...',
  'title': '关于开通伊水游园摆渡车和恢复45路瀍涧大道衡山路以西运营的通告',
  'url': 'https://www.163.com/dy/article/H62CQT770540MBU3.html'},
 {'author': None,
  'cover': 'https://t8.baidu.com/it/u=3444304610,1017160832&fm=217&app=125&size=f242,162&n=0&g=0n&f=JPEG?s=6E5320D6811E45CA08C48C7403004077&sec=1651236167&t=da5a90a958358aaa0395d5b95995babc',
  'date': '3小时前',
  'des': '3、铁岭市经济开发区京抚线G102国道(810km—811km),此处路段(京哈高速桥下),道路变窄,车流量巨大,易发生各类交通事故。 '
         '四、高速公路通行情况 目前铁岭辖区高速公路19个收费站全部双向...',
  'title': '铁岭交警发布2022年“五一”假期出行“两公布一提示”',
  'url': 'https://k.sina.cn/article_2061790953_7ae46ee901900xh6n.html'},
 {'author': None,
  'cover': 'https://t11.baidu.com/it/u=932874032,172013840&fm=30&app=106&size=f242,162&n=0&g=0n&f=JPEG?s=912EDB14C140F34D0498ED640300A031&sec=1651236167&t=703adc2c31a542884599dd5a0c807904',
  'date': '4小时前',
  'des': '目前,该项目正在进行新建道路清表以及素土回填施工。 '
         '据悉,靖远县靖乐公园是当地城市建设的亮点和窗口,更是融“康体休闲、游憩娱乐、生态与文化教育、湿地体验”为一体的城市综合公园。...',
  'title': '中铁一局铁建公司靖乐公园北侧管网及道路新建工程正式开工',
  'url': 'https://baijiahao.baidu.com/s?id=1731339539751895613&wfr=spider&for=pc'},
 {'author': None,
  'cover': None,
  'date': '5小时前',
  'des': '同时,广州市不断加大智能互联汽车开放测试道路力度,近期,海珠区、番禺区等区域再增加106.5公里开放测试道路,为智能网联汽车技术发展与应用示范落地提供坚实保障。 '
         '采写:南都记者梁思华 实习生季炜炜 通讯员 穗统宣胡泽量 编辑:梁思华 【来源...',
  'title': '广州新增106.5公里智能网联汽车开放测试道路',
  'url': 'https://baijiahao.baidu.com/s?id=1731340829845439727&wfr=spider&for=pc'},
 {'author': None,
  'cover': None,
  'date': '今天',
  'des': '2022年区属道路大修(设计) 招标项目的潜在投标人应在详见公告附件获取招标文件,并于2022-05-19 '
         '09:30(北京时间)前递交投标文件。 一、项目基本情况 项目编号:11010622210200001698-XM001 '
         '项目名称:2022年区属道路大修(设计) ...',
  'title': '2022年区属道路大修(设计)公开招标公告',
  'url': 'http://www.mof.gov.cn/gkml/xinxi/difangbiaoxun/difangzhaobiaogonggao/202204/t20220428_17838708.htm'},
 {'author': None,
  'cover': None,
  'date': '6小时前',
  'des': '绿水青山之间,一条条笔直的道路,连接着各族群众的生产生活;一排排整齐排列的砖瓦房,安住着广大群众;一所现代化的校园,书声琅琅;一个生态宜居的小乡村,在乡村振兴的发展中实现着完美蝶变。近年来,扎赉特旗音德尔镇茂力格尔嘎查坚持加强党...',
  'title': '乡村振兴路上开满民族团结幸福花',
  'url': 'https://baijiahao.baidu.com/s?id=1731330770871966289&wfr=spider&for=pc'},
 {'author': None,
  'cover': 'https://t7.baidu.com/it/u=1017634968,1761514231&fm=217&app=125&size=f242,162&n=0&g=0n&f=JPEG?s=9782CBA754A09AE80A3C01B10300B011&sec=1651236167&t=41594f5590af303569d14ce4db9044d2',
  'date': '7小时前',
  'des': '为弘扬爱国卫生优良传统,引导学生养成并实践文明健康绿色环保生活方式,在第34个爱国卫生月来临之际,4月27日,赫山区梓山湖学校开展了“马路小天使——共创文明城” '
         '助力爱国卫生月活动。...',
  'title': '\u200b梓山湖学校:开展“马路小天使——共创文明城” 助力爱国卫生...',
  'url': 'http://www.yyrtv.com/newsDetail-564539.html'},
 {'author': None,
  'cover': 'https://t7.baidu.com/it/u=4019494144,3408804714&fm=217&app=125&size=f242,162&n=0&g=0n&f=JPEG?s=F383E1AC04628EF04A9B3F890300D088&sec=1651236167&t=115770458bcf57c508f2a7603d92dab5',
  'date': '8小时前',
  'des': '网友问:冷东一级公路 什么时候开通城际公交? '
         '冷东一级公路起于冷水滩珊瑚,接中心城区市政道路紫霞路,止于东安县青土坪,路线全长25.9公里,是湖南省“十三五”专项规划项目之一,是市委、...',
  'title': '网友问:冷东一级公路 什么时候开通城际公交?',
  'url': 'https://new.qq.com/omn/20220428/20220428A04M6J00.html'}]
```

**Comment by siblesos** [comment]
最新发现，这里度娘又又又叒改了
##总条数获取
        total = int(
            bs.find("div", id="wrapper_wrapper")
                .find("span", class_="nums")
                .text.split("资讯", 1)[-1]
                .split("篇", 1)[0]
                #.replace(",", "")
                .replace("个", "")
        )
###作者出处获取
 # 作者
            author = _.find("span", class_="c-color-gray").text

**Comment by felixwann** [comment]
> 

谢谢大哥，祝大哥写代码没有BUG

**Comment by Godmyhave** [comment]
又改了。。。。
