### ISSUE TITLE
[BUG]搜索资讯出现“ValueError: invalid literal for int() with base 10: '298个'”的报错

### ISSUE THREAD

**Issue by whycomeing** [BaiduSpider/BaiduSpider#157]
**描述该问题**
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    pprint(spider.search_news(query="卡塔尔", pn=2).plain)
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/__init__.py", line 769, in search_news
    self._handle_error(error)
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/_spider.py", line 90, in _handle_error
    raise err
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/__init__.py", line 763, in search_news
    result = self.parser.parse_news(code)
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/parser/__init__.py", line 558, in parse_news
    total = int(
ValueError: invalid literal for int() with base 10: '298个'
**系统**

- 操作系统: 例如：ubuntu
- Python版本: 3.8

**Comment by gghhzi** [comment]
+10086  I've encountered the same issue as well.

**Comment by gghhzi** [comment]
(D:\conda_envs\python3.9) D:\0\BaiduSpider-dev\hj\BaiduSpider>python 3.py
Traceback (most recent call last):
  File "D:\0\BaiduSpider-dev\hj\BaiduSpider\3.py", line 6, in <module>
    BaiduSpider().search_news('python')
  File "D:\0\BaiduSpider-dev\hj\BaiduSpider\baiduspider\__init__.py", line 769, in search_news
    self._handle_error(error)
  File "D:\0\BaiduSpider-dev\hj\BaiduSpider\baiduspider\_spider.py", line 85, in _handle_error
    raise err
  File "D:\0\BaiduSpider-dev\hj\BaiduSpider\baiduspider\__init__.py", line 763, in search_news
    result = self.parser.parse_news(code)
  File "D:\0\BaiduSpider-dev\hj\BaiduSpider\baiduspider\parser\__init__.py", line 556, in parse_news
    total = int(
ValueError: invalid literal for int() with base 10: '3个'
