### ISSUE TITLE
[BUG]调用例子会报错是为什么呢？

### ISSUE THREAD

**Issue by DearUstinian** [BaiduSpider/BaiduSpider#185]
**描述该问题**
pip install baiduspider后运行例子：

# 导入BaiduSpider
from baiduspider import BaiduSpider
from pprint import pprint

# 实例化BaiduSpider
spider = BaiduSpider()

# 搜索网页
pprint(spider.search_web(query='Python'))

出现报错：
Traceback (most recent call last):
  File "D:\CODE\python\project1\Spider_BD\baidu.py", line 9, in <module>
    pprint(spider.search_web(query='Python'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\pytorch\Lib\site-packages\baiduspider\__init__.py", line 447, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])
                             ^^^^^^^
UnboundLocalError: cannot access local variable 'results' where it is not associated with a value

**预期结果**

请问要怎么解决呢？

**系统**

- 操作系统: windows11
- Python版本: 例如：3.11

**Comment by Kevin9703** [comment]
同问，debug看是返回的页面内容没了，你解决了吗

**Comment by bilibilipala** [comment]
> 同问，debug看是返回的页面内容没了，你解决了吗

内容还在，页面解析需要自己改改
