### ISSUE TITLE
文库搜索报错

### ISSUE THREAD

**Issue by Lay0us** [BaiduSpider/BaiduSpider#195]
**描述该问题**

一个对该问题的清晰的描述。

from baiduspider import BaiduSpider
from pprint import pprint

spider = BaiduSpider()

pprint(spider.search_wenku(query="计算机").plain)
请提供能够复现该问题的代码或步骤。

**预期结果**

一个对你想要的结果的清晰的描述。

Traceback (most recent call last):
  File "/root/code_demo/python_demo/2024/baiduwenku/main.py", line 6, in <module>
    pprint(spider.search_wenku(query="计算机").plain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/baiduspider/__init__.py", line 943, in search_wenku
    self._handle_error(error)
  File "/usr/local/lib/python3.12/dist-packages/baiduspider/_spider.py", line 96, in _handle_error
    raise err
  File "/usr/local/lib/python3.12/dist-packages/baiduspider/__init__.py", line 936, in search_wenku
    code = self._get_response(url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/baiduspider/_spider.py", line 84, in _get_response
    content = bytes(response.text, response.encoding).decode("utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 125: invalid start byte
                                                                                              

**系统**

- 操作系统: Kali linux
- Python版本: 
- └─# python3 -V
Python 3.12.6

**其他描述**

一些关于问题的其他的描述。

**Comment by Lay0us** [comment]
调试之后发现为百度返回内容问题，parser/__init__.py更新代码即可
![1](https://github.com/user-attachments/assets/bfede8c8-bc2e-4fd0-87d6-b6d5a6125a04)
