### ISSUE TITLE
[BUG] baiduspider.errors.ParseError: Invalid control character at: line 1 column 60799 (char 60798)

### ISSUE THREAD

**Issue by ZillyRex** [BaiduSpider/BaiduSpider#2]
my code:
```
from baiduspider import BaiduSpider
from pprint import pprint

if __name__ == "__main__":
    keyword = '道路破损'
    max_page = 100

    spider = BaiduSpider()
    for pn in range(max_page):
        pprint(spider.search_pic(keyword, pn))
```

after about 30 iter, I get:

```
Traceback (most recent call last):
  File ".\spider_data.py", line 11, in <module>
    pprint(spider.search_pic(keyword, pn))
  File "C:\Users\YCKJ3341\Miniconda3\envs\pytorch\lib\site-packages\baiduspider\__init__.py", line 232, in search_pic
    self._handle_error(error)
  File "C:\Users\YCKJ3341\Miniconda3\envs\pytorch\lib\site-packages\baiduspider\_spider.py", line 71, in _handle_error
    raise error
  File "C:\Users\YCKJ3341\Miniconda3\envs\pytorch\lib\site-packages\baiduspider\__init__.py", line 228, in search_pic
    result = self.parser.parse_pic(content)
  File "C:\Users\YCKJ3341\Miniconda3\envs\pytorch\lib\site-packages\baiduspider\parser.py", line 288, in parse_pic
    if error: raise ParseError(str(error))
baiduspider.errors.ParseError: Invalid control character at: line 1 column 60799 (char 60798)
```

System:

OS : Windows 10
python : 3.6.10

How can I fix this problem？

**Comment by samzhangjy** [comment]
We've noticed this issue and is working on it. More updates will be posted in this issue. Thanks for telling us!

**Comment by iewoai** [comment]
@ZillyRex try in baiduspider\parser.py, line 282:
data = json.loads(content.split('flip.setData(\'imgData\', ')[1].split(
                'flip.setData(')[0].split(']);')[0].replace(');', '').replace('<\\/strong>', '</strong>').replace('\\\'', '\''), strict=False)

**Comment by samzhangjy** [comment]
问题已经修复，如果有其他问题请重新开启issue。
