### ISSUE TITLE
[BUG] Basic `BaiduSpider()` does not work.

### ISSUE THREAD

**Issue by qzweng** [BaiduSpider/BaiduSpider#31]
**描述该问题**

Basic `BaiduSpider()` does not work. (Is it blocked by Baidu? The same code had worked perfectly fine.)

**复现该问题**

```bash
➜  ~ python
Python 3.9.4 (default, Apr  5 2021, 01:49:30)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from baiduspider import BaiduSpider
>>> spider = BaiduSpider()
>>> spider.search_news(query="Hello", pn=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/baiduspider/__init__.py", line 499, in search_news
    self._handle_error(error)
  File "/usr/local/lib/python3.9/site-packages/baiduspider/_spider.py", line 68, in _handle_error
    raise err
  File "/usr/local/lib/python3.9/site-packages/baiduspider/__init__.py", line 493, in search_news
    result = self.parser.parse_news(code)
  File "/usr/local/lib/python3.9/site-packages/baiduspider/parser/__init__.py", line 461, in parse_news
    res.find("div", class_="c-span-last")
AttributeError: 'NoneType' object has no attribute 'find'
>>>
```

Similar for IPython
```bash
➜  ~ export DEBUG=1
➜  ~ ipython
Python 3.9.4 (default, Apr  5 2021, 01:49:30)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from baiduspider import BaiduSpider

In [2]: spider = BaiduSpider()

In [3]: results = spider.search_news(query="Hello", pn=0)['results']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-4d3b276d2fa8> in <module>
----> 1 results = spider.search_news(query="Hello", pn=0)['results']

/usr/local/lib/python3.9/site-packages/baiduspider/__init__.py in search_news(self, query, pn)
    497         finally:
    498             if error:
--> 499                 self._handle_error(error)
    500         return {"results": result["results"], "total": result["pages"]}
    501

/usr/local/lib/python3.9/site-packages/baiduspider/_spider.py in _handle_error(self, err, parent, cause)
     66             return None
     67         if bool(int(os.environ.get("DEBUG", 0))):
---> 68             raise err
     69         else:
     70             print(

/usr/local/lib/python3.9/site-packages/baiduspider/__init__.py in search_news(self, query, pn)
    491             # 压缩
    492             code = self._minify(source.text)
--> 493             result = self.parser.parse_news(code)
    494             result = result if result is not None else self.EMPTY
    495         except Exception as err:

/usr/local/lib/python3.9/site-packages/baiduspider/parser/__init__.py in parse_news(self, content)
    459             # 作者
    460             author = (
--> 461                 res.find("div", class_="c-span-last")
    462                 .find("div", class_="news-source")
    463                 .find("span", class_="c-gap-right")

AttributeError: 'NoneType' object has no attribute 'find'
```

**预期结果**

`spider.search_news(query="Hello", pn=0)` should return normally.

**实际结果**

Error

**系统**

- macOS Catalina, 10.15.7
- Python 3.9.4
- baiduspider build on May 27
```bash
➜  baiduspider ll
total 72
drwxr-xr-x    8 muchong  admin    256 May 27 09:28 ./
drwxr-xr-x  193 muchong  admin   6176 Jun 17 11:37 ../
-rw-r--r--    1 muchong  admin  26149 May 27 09:28 __init__.py
drwxr-xr-x    5 muchong  admin    160 May 27 09:28 __pycache__/
-rw-r--r--    1 muchong  admin   3252 May 27 09:28 _spider.py
drwxr-xr-x    4 muchong  admin    128 May 27 09:28 errors/
drwxr-xr-x    5 muchong  admin    160 May 27 09:28 parser/
-rw-r--r--    1 muchong  admin   1913 May 27 09:28 util.py
➜  baiduspider pwd
/usr/local/lib/python3.9/site-packages/baiduspider
```

**其他描述**

N/A

**Comment by samzhangjy** [comment]
Hi. Thank you for reporting this issue. This issue was fixed in the next version, BaiduSpider `V1.0`, which will release the Preview Version in the next few days. Thank you!

If you have any questions, feel free to ask!
